name: Deploy MultiDocker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
 
      - run: docker build -t vislike/multi-client ./client
      - run: docker build -t vislike/multi-nginx ./nginx
      - run: docker build -t vislike/multi-server ./server
      - run: docker build -t vislike/multi-worker ./worker
 
      - run: docker push vislike/multi-client
      - run: docker push vislike/multi-nginx
      - run: docker push vislike/multi-server
      - run: docker push vislike/multi-worker